spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${SPRING_DATASOURCE_DB_NAME:incident_management}
    username: ${SPRING_DATASOURCE_USERNAME:abhishek}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
